# Generated by Django 4.0.5 on 2022-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='from_name',
            field=models.CharField(default='Airport', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='to_name',
            field=models.CharField(default='Home', max_length=100),
            preserve_default=False,
        ),
    ]
